upstream_server: "192.168.88.3"

services_path:
  user-transaction:
    src_path: "/home/domestic/user-transaction/"
    dest_path: "/home/domestic/user-transaction/"
  VisitorManager:
    src_path: "/home/visitordev/visitorManager/visitormanager_backend/"
    dest_path: "/home/visitor/manager/"
