---
- name: Deploy Java Microservice
  hosts: all
#  hosts: localhost
#  connection: local
  serial: 1  # This ensures "Rolling Update" (one server at a time)
  become: yes
#  vars_files:
#    vars/jar.yml
#  vars:
#    deploy_path: "/opt/{{ app_name }}"
#    release_path: "{{ deploy_path }}/releases/{{ version }}"

  tasks:
#    - name: Create release directory
#      ansible.builtin.file:
#        path: "{{ release_path }}"
#        state: directory
    - name: Ensure local fetch directory exists
      ansible.builtin.file:
        path: "/tmp/fetched"
        state: directory
      delegate_to: localhost
      become: no

    - block:
        - name: Pull Java JAR from staging to semaphore
          delegate_to: "{{ upstream_server }}"
          vars:
            ansible_user: "ansible"
          ansible.builtin.fetch:
            src: "{{ item.value.src_path }}/{{ jar_name }}-{{ jar_version }}-jar-with-dependencies.jar"
            dest: "/tmp/fetched/{{ jar_name }}-{{ jar_version }}-jar-with-dependencies.jar"
            flat: yes
          loop: "{{ services_path | dict2items }}"
          when: item.key == jar_name
          check_mode: no
  
        - name: Push Java JAR from semaphore to production
          ansible.builtin.copy:
            src: "/tmp/fetched/{{ jar_name }}-{{ jar_version }}-jar-with-dependencies.jar"
            dest: "{{ item.value.dest_path }}/{{ jar_name }}-{{ jar_version }}-jar-with-dependencies.jar"
          loop: "{{ services_path | dict2items }}"
          when: item.key == jar_name
  
        - name: Update JAR version 
          ansible.builtin.replace:
            path: "{{ item.value.dest_path }}/etc/config.properties"
            regexp: '^VERSION=.*' 
            replace: "VERSION={{ jar_version }}"
            backup: yes
          loop: "{{ services_path | dict2items }}"
          when: item.key == jar_name
  
      always:
        - name: Delete the temporary Java JAR on semaphore
          ansible.builtin.file:
            path: "/tmp/fetched/"
            state: absent
          delegate_to: localhost
          run_once: true
          become: no
  
#    - name: Upload Java JAR
#      copy:
#        src: "./target/app-{{ version }}.jar"
#        dest: "{{ release_path }}/app.jar"

#    - name: Upload Java JAR
#      copy:
#        src: "~/java-multi-microservices/bjava/target/bjava-{{ version }}.jar"
#        dest: "{{ release_path }}/app.jar"

#    - name: Run Database Migrations (Only on the first host)
#      command: java -jar {{ release_path }}/app.jar --migrate
#      when: inventory_hostname == groups['backend_servers'][0]

#    - name: Update symlink to new version
#      file:
#        src: "{{ release_path }}"
#        dest: "{{ deploy_path }}/current"
#        state: link

#    - name: Execute my custom script
#      ansible.builtin.script: deployment.sh
#      args:
#        executable: /bin/bash
        
#    - name: Restart systemd service
#      systemd:
#        name: "{{ app_name }}"
#        state: restarted
#        daemon_reload: yes

#    - name: Wait for Health Check
#      uri:
#        url: "http://localhost:8080/actuator/health"
#        status_code: 200
#      register: result
#      until: result.status == 200
#      retries: 10
#      delay: 5
