[production]
sinkamari ansible_host=10.10.80.10 ansible_user=ansible

[staging]
sinkamari-stag ansible_host=10.10.60.10 ansible_user=ansible

[test]
test ansible_host=192.168.88.3 ansible_user=ansible
